# Generated by Django 3.0.7 on 2020-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('slices', models.IntegerField(default=0)),
                ('cutlets', models.IntegerField(default=0)),
                ('salad', models.BooleanField(default=False)),
                ('buns', models.IntegerField(default=2)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('cost', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
